# Generated by Django 5.1.1 on 2024-10-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_images/d_profile.png', null=True, upload_to='profile_images'),
        ),
    ]
