# Generated by Django 5.1.1 on 2024-10-27 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_user_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
    ]
