# Generated by Django 5.1.1 on 2024-10-01 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
