# Generated by Django 5.1.1 on 2024-10-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serial', '0004_alter_serial_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serial',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, null=True, unique=True),
        ),
    ]
