# Generated by Django 5.1.1 on 2024-10-25 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serial', '0008_serialepisode'),
    ]

    operations = [
        migrations.AddField(
            model_name='serial',
            name='Duration',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
