# Generated by Django 5.1.1 on 2024-10-25 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serial', '0009_serial_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serial',
            old_name='Duration',
            new_name='duration',
        ),
    ]
