# Generated by Django 5.1.1 on 2024-11-01 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serial', '0011_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serial',
            options={'ordering': ('-created_at',)},
        ),
    ]
